---
- name: Clean and recreate Elasticsearch keystore
  hosts: all
  become: yes

  tasks:
    - name: Remove existing Elasticsearch keystore
      command: rm -f /etc/elasticsearch/elasticsearch.keystore

    - name: Recreate empty Elasticsearch keystore as root
      command: /usr/share/elasticsearch/bin/elasticsearch-keystore create
